# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gC0GqKp9zwcTPPr8JzoQ8xIw_6vQo0_M
"""



import pandas as pd

df = pd.read_csv("volume_turnover_aum_data_new.csv")

# Convert date column explicitly
df["date"] = pd.to_datetime(df["date"], format="%d-%b-%y", errors="coerce")

# Check if any conversion issues occurred
if df["date"].isna().sum() > 0:
    print("Warning: Some date values could not be converted!")

# Reformat date
df["date"] = df["date"].dt.strftime("%Y-%m-%d")

# Rename columns to match the required format
df.columns = ["date", "volume_9008", "volume_9042", "volume_9439", "turnover_9008", "turnover_9042", "turnover_9439"]

# Reorder columns
df = df[["date", "volume_9008", "turnover_9008", "volume_9042", "turnover_9042", "volume_9439", "turnover_9439"]]

# Save the modified CSV
df.to_csv("volume_turnover_aum_data_new.csv", index=False)

print("CSV file has been reformatted and saved as formatted_file.csv")




